/* auto-generated by NAPI-RS */
/**
 * Persistent R4 project state. All public methods exchange JSON strings so
 * the existing hostile-input limits and structured-error contract stay at the
 * napi boundary, while the graph itself never crosses that boundary.
 */
export declare class ProjectHandle {
  constructor(inputJson: string)
  applyChanges(eventsJson: string): string
  provideCallbackResults(resultsJson: string): string
  setOverlay(path: string, content: string): string
  clearOverlay(path: string): string
  getResult(): string
  getReachedFiles(): string
}

export declare function analyzeProject(inputJson: string): string

/**
 * Test-only R2 seam for comparing one Rust resolution with
 * `ts.resolveModuleName` without discarding external-library paths.
 */
export declare function resolveModuleNameForEngineShadow(inputJson: string): string

/**
 * Shadow-only R2 entry point. The production TypeScript resolver remains the
 * default until the later consumer cutover phase.
 */
export declare function resolveProjectImports(inputJson: string): string
