// Generates a large synthetic Sheriff project for benchmarking.
// Layout: src/app/<domain>/<module>/ modules with index.ts barrels.
import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, parse, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const DEFAULTS = {
  domains: 100,
  modulesPerDomain: 3,
  filesPerModule: 6,
};
const MARKER_FILE = '.sheriff-perf-project';

export function generateBenchProject(root, options = {}) {
  const settings = { ...DEFAULTS, ...options };
  validateSettings(settings);

  const projectRoot = safeProjectRoot(root);
  if (existsSync(projectRoot) && !existsSync(join(projectRoot, MARKER_FILE))) {
    throw new Error(
      `Refusing to replace ${projectRoot}: it was not created by this benchmark generator.`,
    );
  }
  rmSync(projectRoot, { recursive: true, force: true });
  const src = join(projectRoot, 'src');
  mkdirSync(src, { recursive: true });
  writeFileSync(join(projectRoot, MARKER_FILE), 'generated by Sheriff perf\n');

  const moduleTypes = createModuleTypes(settings.modulesPerDomain);
  const mainImports = [];

  for (let domain = 0; domain < settings.domains; domain++) {
    mainImports.push(
      `import { api as d${domain} } from './app/domain-${domain}/${moduleTypes[0]}';`,
    );

    for (let module = 0; module < moduleTypes.length; module++) {
      const type = moduleTypes[module];
      const directory = join(src, 'app', `domain-${domain}`, type);
      mkdirSync(directory, { recursive: true });

      const barrel = [];
      for (let file = 0; file < settings.filesPerModule; file++) {
        writeFileSync(
          join(directory, `file-${file}.ts`),
          fileBody(domain, module, file, moduleTypes, settings),
        );
        barrel.push(`export { fn_${type}_${file} } from './file-${file}';`);
      }
      barrel.push(`export const api = ${domain};`);
      writeFileSync(join(directory, 'index.ts'), `${barrel.join('\n')}\n`);
    }
  }

  writeFileSync(
    join(src, 'main.ts'),
    `${mainImports.join('\n')}\n\nconsole.log(${Array.from(
      { length: settings.domains },
      (_, domain) => `d${domain}`,
    ).join(' + ')});\n`,
  );
  writeFileSync(
    join(projectRoot, 'tsconfig.json'),
    `${JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'ESNext',
          moduleResolution: 'bundler',
          strict: true,
          baseUrl: './src',
        },
        include: ['src/**/*.ts'],
      },
      null,
      2,
    )}\n`,
  );
  writeFileSync(
    join(projectRoot, 'sheriff.config.ts'),
    `import { SheriffConfig, sameTag } from '@lambda-solutions/sheriff-core';

export const config: SheriffConfig = {
  version: 1,
  entryFile: 'src/main.ts',
  tagging: {
    'src/app': {
      '<domain>/<type>': ['domain:<domain>', 'type:<type>'],
    },
  },
  depRules: {
    root: ['type:*'],
    'domain:*': [sameTag, 'domain:*'],
    'type:*': ['type:*'],
  },
};
`,
  );

  return {
    root: projectRoot,
    files:
      settings.domains *
        settings.modulesPerDomain *
        (settings.filesPerModule + 1) +
      1,
    ...settings,
  };
}

function fileBody(domain, module, file, moduleTypes, settings) {
  const type = moduleTypes[module];
  const lines = [];
  const siblingCount = Math.min(3, settings.filesPerModule - 1);

  for (let offset = 1; offset <= siblingCount; offset++) {
    const sibling = (file + offset) % settings.filesPerModule;
    lines.push(`import { fn_${type}_${sibling} } from './file-${sibling}';`);
  }
  if (file === 0 && module + 1 < moduleTypes.length) {
    lines.push(
      `import { api as nextApi } from '../${moduleTypes[module + 1]}';`,
    );
  }
  if (file === 0 && module === 0) {
    const nextDomain = (domain + 1) % settings.domains;
    lines.push(
      `import { api as otherApi } from '../../domain-${nextDomain}/${type}';`,
    );
  }
  lines.push(
    '',
    `export function fn_${type}_${file}(): number {`,
    `  return ${file};`,
    '}',
  );
  return `${lines.join('\n')}\n`;
}

function createModuleTypes(count) {
  const conventionalTypes = ['feature', 'data', 'model'];
  return Array.from(
    { length: count },
    (_, index) => conventionalTypes[index] ?? `module-${index}`,
  );
}

function validateSettings(settings) {
  for (const [name, value] of Object.entries(settings)) {
    if (!Number.isInteger(value) || value < 1) {
      throw new Error(`${name} must be a positive integer`);
    }
  }
}

function safeProjectRoot(root) {
  if (!root) {
    throw new Error(
      'Usage: node tools/perf/gen-bench.mjs <root> [domains] [modulesPerDomain] [filesPerModule]',
    );
  }

  const projectRoot = resolve(root);
  if (
    projectRoot === parse(projectRoot).root ||
    projectRoot === process.cwd()
  ) {
    throw new Error(
      `Refusing to replace unsafe benchmark root: ${projectRoot}`,
    );
  }
  mkdirSync(dirname(projectRoot), { recursive: true });
  return projectRoot;
}

const invokedPath = process.argv[1]
  ? pathToFileURL(resolve(process.argv[1])).href
  : undefined;
if (invokedPath === import.meta.url) {
  const result = generateBenchProject(process.argv[2], {
    domains: Number(process.argv[3] ?? DEFAULTS.domains),
    modulesPerDomain: Number(process.argv[4] ?? DEFAULTS.modulesPerDomain),
    filesPerModule: Number(process.argv[5] ?? DEFAULTS.filesPerModule),
  });
  console.log(`generated ${result.files} TS files in ${result.root}`);
}
